// ng-generic-store/src/app/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {

  constructor() { }
  currentYear = new Date().getFullYear();

}

<div class="footer">
    <p class="footer-text">
        <span class="copyleft">&copy;</span> {{currentYear}} All Rights Reversed.
    </p>
</div>

// react-store-managment/src/Footer/Footer.jsx
import React from 'react';
import './Footer.css'

class Footer extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div className="footer">
                <p className="footer-text">
                    <span className="copyleft">&copy;</span> {(new Date()).getFullYear()} All Rights Reversed.
                </p>
            </div>
        )
    }
}

export default Footer
